# This is a basic workflow to help you get started with Actions

name: Test Kubes Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: ${{ secrets.DEVELOPMENT_EB_ENVIRONMENT_NAME }}
      IMAGE_TAG: ${{ github.SHA }}
      IMAGE_NAME: findigs-core-api
      DOCKER_REGISTRY: 267485056628.dkr.ecr.us-east-1.amazonaws.com

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

